version: '3.8'

services:
  # ========== БД ==========
  db:
    image: postgres:17
    restart: always
    env_file:
      - backend/.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # ========== Redis ( кеш + брокер Celery ) ==========
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # ========== Django-бекенд ==========
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app

  # ========== Celery worker ==========
  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A config worker --pool=solo --loglevel=info
    env_file:
      - backend/.env
    depends_on:
      - backend
      - redis

  # ========== Celery beat ==========
  celery_beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A config beat --loglevel=info
    env_file:
      - backend/.env
    depends_on:
      - backend
      - redis

  # ========== Next.js ==========
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    volumes:
      - ./frontend/public:/usr/share/nginx/html

volumes:
  db_data:
  redis_data:
