# Generated by Django 5.2 on 2025-05-19 12:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Given name",
                        max_length=100,
                        verbose_name="first name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Family name",
                        max_length=100,
                        verbose_name="last name",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="Postal address",
                        null=True,
                        verbose_name="address",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Include country code, e.g., +1-202-555-0123",
                        max_length=20,
                        verbose_name="phone number",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Contact email",
                        max_length=254,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "birthday",
                    models.DateField(
                        blank=True,
                        help_text="Date of birth",
                        null=True,
                        verbose_name="birthday",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Record creation timestamp",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Record last modification timestamp",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Власник контакту",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "contact",
                "verbose_name_plural": "contacts",
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
