# Generated by Django 5.2 on 2025-04-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="address",
            field=models.TextField(
                blank=True,
                help_text="Postal address",
                null=True,
                verbose_name="address",
            ),
        ),
    ]
