# Generated by Django 5.2 on 2025-05-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guid", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=500)),
                ("link", models.URLField()),
                ("description", models.TextField(blank=True)),
                ("pub_date", models.DateTimeField()),
            ],
            options={
                "ordering": ["-pub_date"],
            },
        ),
    ]
