# Generated by Django 5.2 on 2025-05-19 12:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("content", models.TextField(verbose_name="content")),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated keywords",
                        max_length=200,
                        verbose_name="tags",
                    ),
                ),
                (
                    "reminder_date",
                    models.DateField(
                        blank=True,
                        help_text="Optional reminder date in the future",
                        null=True,
                        verbose_name="reminder date",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("", "None"),
                            ("green", "Completed"),
                            ("yellow", "Pending"),
                            ("red", "Failed"),
                        ],
                        default="",
                        help_text="Color label: green/completed, yellow/pending, red/failed",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Власник нотатки",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
