# Generated by Django 5.2 on 2025-05-19 12:55

import django.db.models.deletion
import files.models
import storages.backends.s3
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "file",
                    models.FileField(
                        storage=storages.backends.s3.S3Storage(
                            bucket_name="personal-assistant-aws",
                            custom_domain="personal-assistant-aws.s3.eu-west-2.amazonaws.com",
                        ),
                        upload_to=files.models.upload_to_uuid_by_ext,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("document", "Document"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=10,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Image owner",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
